apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentburg

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - server-deployment.yaml
  - dashboard.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: agentburg
