"""add_season_model_and_agent_season_fk

Revision ID: 506ef1fa18a2
Revises: 7fd27461d275
Create Date: 2026-03-23 20:58:59.196754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '506ef1fa18a2'
down_revision: Union[str, None] = '7fd27461d275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'ended', name='seasonstatus'), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_tick', sa.Integer(), nullable=True),
    sa.Column('end_tick', sa.Integer(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('season_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_agents_season_id'), 'agents', ['season_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_season_id'), table_name='agents')
    op.drop_column('agents', 'season_id')
    op.drop_table('seasons')
    # ### end Alembic commands ###
