"""add_agent_position_columns

Revision ID: 7fd27461d275
Revises: 001
Create Date: 2026-03-23 14:46:15.401176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd27461d275'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('pos_x', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('pos_y', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'pos_y')
    op.drop_column('agents', 'pos_x')
    # ### end Alembic commands ###
